### ISSUE TITLE
OVD 1.0 - flow issue

### ISSUE THREAD

**Issue by batevladi** [bacgroup/man_ovd_client#33]
When no connection or connection fails with OVD server, the client does not return to login screen. (ubuntu 16.04 - .deb package)

**Comment by batevladi** [comment]
Ubuntu (linux - .deb package) - dependence on FreeRDP (vanilla - freerdp-x11) missing in version 1.0, required for the package to run.

**Comment by salvatoretrimarchi** [comment]
Hello @batevladi 

Thank you for the isssue.

I resolve that in ALPHA Realease please try it.

https://github.com/bacgroup/man_ovd_client/releases/tag/man_ovd_client_7_ALPHA-feature_man_ovd_client_2.0
